name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm install --frozen-lockfile

      # - name: 🚧 Set up project
        # run: npm dev:prepare

      - name: 🛠 Build project
        run: npm build

      - name: 🧪 Test project
        run: npm test

      - name: 🟩 Coverage
        uses: codecov/codecov-action@v4
